---
sudo: false
dist: xenial
language: python
python: 3.7
before_install: ls -1 /opt/python
install: pip install tox
script: tox

jobs:
  include:
    - env: TOXENV=py37
    - env: TOXENV=py37-27sub
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py38
      python: 3.8
